<?php

class ContactUsController extends ControllerBase
{
    const POST_CONTACTUS = "https://api.butlerfly.com/send/contactus";

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){

        if ($this->request->isPost()) {

            $firstname = $this->request->getPost('firstname');
            $lastname  = $this->request->getPost('lastname');
            $email     = $this->request->getPost('email');
            $phone     = $this->request->getPost('phone');
            $question  = $this->request->getPost('question');
            $message   = $this->request->getPost('message');

            echo $firstname."<br/>";
            echo $lastname."<br/>";
            echo $email."<br/>";
            echo $phone."<br/>";
            echo $question."<br/>";
            echo $message."<br/>";

            $json = "{\"Name\":\"$firstname $lastname\",\"Email\":\"$email\",\"Phone\":\"$phone\",\"Question\":\"$question\",\"Message\":\"$message\"}";

            $result = RestApi::PostRequest($this::POST_CONTACTUS,$json);

            if($result->ContactUs == 'OK'){
                $this->dispatcher->forward(array(
                    'controller' => 'contactus',
                    'action' => 'success',
                ));
            }
            else {
                $this->dispatcher->forward(array(
                    'controller' => 'contactus',
                    'action' => 'error',
                ));
            }

        }

    }

    public function errorAction(){

    }
    public function successAction(){

    }
}

