<?php

class IndexController extends ControllerBase
{

    protected $sys;

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){

        $sys = new ButlerflyServices();

        $action = "availability/";

        $this->view->setVar('urlHousekeeping'    ,$action.$sys::KEY_HOUSEKEEPING);
        $this->view->setVar('urlMovingHelp'      ,$action.$sys::KEY_MOVINGHELP);
        $this->view->setVar('urlDisposal'        ,$action.$sys::KEY_DISPOSAL);
        $this->view->setVar('urlYardMaintenance' ,$action.$sys::KEY_YARDMAINTENANCE);
        $this->view->setVar('urlPickupDelivery'  ,$action.$sys::KEY_PICKUPANDDELIVERY);
        $this->view->setVar('urlHandyman'        ,$action.$sys::KEY_HANDYMAN);
        $this->view->setVar('urlHeatingCooling'  ,$action.$sys::KEY_HEATINGANDCOOLING);
        $this->view->setVar('urlSnowRemoval'     ,$action.$sys::KEY_SNOWREMOVAL);
        $this->view->setVar('urlErrandsChores'   ,$action.$sys::KEY_ERRANDSANDCHORES);

        $this->view->setVar('nameHousekeeping'    ,$sys::NAME_HOUSEKEEPING);
        $this->view->setVar('nameMovingHelp'      ,$sys::NAME_MOVINGHELP);
        $this->view->setVar('nameDisposal'        ,$sys::NAME_DISPOSAL);
        $this->view->setVar('nameYardMaintenance' ,$sys::NAME_YARDMAINTENANCE);
        $this->view->setVar('namePickupDelivery'  ,$sys::NAME_PICKUPANDDELIVERY);
        $this->view->setVar('nameHandyman'        ,$sys::NAME_HANDYMAN);
        $this->view->setVar('nameHeatingCooling'  ,$sys::NAME_HEATINGANDCOOLING);
        $this->view->setVar('nameSnowRemoval'     ,$sys::NAME_SNOWREMOVAL);
        $this->view->setVar('nameErrandsChores'   ,$sys::NAME_ERRANDSANDCHORES);

    }

    public function contactAction(){
        $form = new ContactUsForm();
        $this->view->form = $form;
    }

    public function termsAction(){ }

    public function supportAction(){ }

    public function nocoverageAction($zipcode,$id){

        $sys = new ButlerflyServices();
        $name = $sys->getServiceNameById($id);
        $desc = $sys->getServiceDescriptionById($id);
        $this->view->setVar('name',$name);
        $this->view->setVar('desc',$desc);
        $this->view->setVar('zipcode',$zipcode);
    }

    public function availabilityAction(){

        $key = $this->dispatcher->getParam('service');

        $sys = new ButlerflyServices();

        $id = $sys->getServiceIdByKey($key);
        $name = $sys->getServiceNameById($id);
        $desc = $sys->getServiceDescriptionById($id);

        $this->view->setVar('index',$id);
        $this->view->setVar('name',$name);
        $this->view->setVar('desc',$desc);

        $form = new AvailabilityForm();
        $zipcodes = $sys->getZipcodes();

        if ($this->request->isPost()) {
            if ($form->isValid($this->request->getPost()) != false) {

                $zipcode = $this->request->getPost('zipcode');
                $service = $this->request->getPost('service');
                $name    = $sys->getServiceNameById($id);

                if(in_array($zipcode, $zipcodes)){
                    $this->dispatcher->forward([
                        'controller' => 'service',
                        'action' => $sys->getActionById($id),
                        'params' => [$zipcode,$service,$name]
                    ]);
                }
                else{
                    $this->dispatcher->forward([
                        'controller' => 'index',
                        'action' => 'nocoverage',
                        'params' => [$zipcode,$id]
                    ]);
                }
            }
        }
        $this->view->form = $form;
    }

}