<?php

class ServiceController extends FormControllerBase
{
    protected $sys;

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->sys = new ButlerflyServices();
    }

    public function indexAction(){
        $this->response->redirect('//butlerfly.com');
        $this->view->disable();
    }

    public function submittedAction($id){
        $name    = $this->sys->getServiceNameById($id);
        $desc    = $this->sys->getServiceDescriptionById($id);
        $this->view->setVar('name',$name);
        $this->view->setVar('desc',$desc);
    }
    public function errorAction($id){

        $name    = $this->sys->getServiceNameById($id);
        $desc    = $this->sys->getServiceDescriptionById($id);

        $this->view->setVar('name',$name);
        $this->view->setVar('desc',$desc);

    }

    public function housekeepingAction(){ $this->housekeepingForm(); }
    public function movinghelpAction(){ $this->movinghelpForm(); }
    public function disposalAction(){ $this->disposalForm(); }
    public function yardmaintenanceAction(){ $this->yardmaintenanceForm(); }
    public function yardcleanupAction(){ $this->standardForm(); }
    public function pickupanddeliveryAction(){ $this->pickupForm(); }
    public function handymanAction(){ $this->standardForm(); }
    public function heatingandcoolingAction(){ $this->standardForm(); }
    public function snowremovalAction(){ $this->standardForm(); }
    public function errandsandchoresAction(){ $this->standardForm(); }

    public function submitAction(){
        if ($this->request->isPost()) {

            $post = $this->request->getPost();

            $date = DateTime::createFromFormat('U.u', microtime(true));
            $n = $date->format('YmdHisu');
            $idrequest = substr($n,0,count($n)-3);

            unset($post['approve']);
            unset($post['g-recaptcha-response']);

            $post['idrequest'] = $idrequest;
            $post['state']     = "MI";
            $post['ctype']     = $this->sys->encrypt($post['ctype']); // base64_encode($post['ctype'].$key);
            $post['cnumber']   = $this->sys->encrypt($post['cnumber']); // base64_encode($post['cnumber'].$key);
            $post['cmonth']    = $this->sys->encrypt($post['cmonth']); // base64_encode($post['cmonth'].$key);
            $post['cyear']     = $this->sys->encrypt($post['cyear']); // base64_encode($post['cyear'].$key);
            $post['cscode']    = $this->sys->encrypt($post['cscode']); // base64_encode($post['cscode'].$key);
            $post['cholder']   = $this->sys->encrypt($post['cholder']); // base64_encode($post['cholder'].$key);
            $post['caddress']  = $this->sys->encrypt($post['caddress']); // base64_encode($post['caddress'].$key);
            $post['ccity']     = $this->sys->encrypt($post['ccity']); // base64_encode($post['ccity'].$key);
            $post['cstate']    = $this->sys->encrypt($post['cstate']); // base64_encode($post['cstate'].$key);
            $post['czipcode']  = $this->sys->encrypt($post['czipcode']); // base64_encode($post['czipcode'].$key);

            $this->dispatcher->forward([
                'controller' => 'order',
                'action' => 'send',
                'params' => [$post]
            ]);
        }
    }

    private function standardForm(){
        if ($this->request->isPost()) {
            $zipcode = $this->request->getPost('zipcode');
            $service = $this->request->getPost('service');
            $rate    = $this->sys->getRateById($service);
            $name    = $this->sys->getServiceNameById($service);
            $desc    = $this->sys->getServiceDescriptionById($service);
            $smsg    = $this->sys->getServiceMessage();
            $this->view->setVar('zipcode',$zipcode);
            $this->view->setVar('service',$service);
            $this->view->setVar('rate',$rate);
            $this->view->setVar('name',$name);
            $this->view->setVar('desc',$desc);
            $this->view->setVar('smsg',$smsg);
            $this->view->form = new StandardServiceForm();
        }
    }

    private function housekeepingForm(){
        if ($this->request->isPost()) {
            $zipcode = $this->request->getPost('zipcode');
            $service = $this->request->getPost('service');
            $rate    = $this->sys->getRateById($service);
            $name    = $this->sys->getServiceNameById($service);
            $desc    = $this->sys->getServiceDescriptionById($service);
            $smsg    = $this->sys->getServiceMessage();
            $this->view->setVar('zipcode',$zipcode);
            $this->view->setVar('service',$service);
            $this->view->setVar('rate',$rate);
            $this->view->setVar('name',$name);
            $this->view->setVar('desc',$desc);
            $this->view->setVar('smsg',$smsg);
            $this->view->form = new HousekeepingServiceForm();
        }
    }

    private function movinghelpForm(){
        if ($this->request->isPost()) {
            $zipcode = $this->request->getPost('zipcode');
            $service = $this->request->getPost('service');
            $rate    = $this->sys->getRateById($service);
            $name    = $this->sys->getServiceNameById($service);
            $desc    = $this->sys->getServiceDescriptionById($service);
            $smsg    = $this->sys->getServiceMessage();
            $this->view->setVar('zipcode',$zipcode);
            $this->view->setVar('service',$service);
            $this->view->setVar('rate',$rate);
            $this->view->setVar('name',$name);
            $this->view->setVar('desc',$desc);
            $this->view->setVar('smsg',$smsg);
            $this->view->form = new MovingServiceForm();
        }
    }

    private function pickupForm(){
        if ($this->request->isPost()) {
            $zipcode  = $this->request->getPost('zipcode');
            $service  = $this->request->getPost('service');
            $rate     = $this->sys->getRateById($service);
            $name    = $this->sys->getServiceNameById($service);
            $desc    = $this->sys->getServiceDescriptionById($service);
            $smsg    = $this->sys->getServiceMessage();
            $this->view->setVar('zipcode',$zipcode);
            $this->view->setVar('service',$service);
            $this->view->setVar('rate',$rate);
            $this->view->setVar('name',$name);
            $this->view->setVar('desc',$desc);
            $this->view->setVar('smsg',$smsg);
            $this->view->form = new PickupServiceForm();
        }
    }

    private function disposalForm(){
        if ($this->request->isPost()) {
            $zipcode = $this->request->getPost('zipcode');
            $service = $this->request->getPost('service');
            $rate    = $this->sys->getRateById($service);
            $name    = $this->sys->getServiceNameById($service);
            $desc    = $this->sys->getServiceDescriptionById($service);
            $smsg    = $this->sys->getServiceMessage();
            $this->view->setVar('zipcode',$zipcode);
            $this->view->setVar('service',$service);
            $this->view->setVar('rate',$rate);
            $this->view->setVar('name',$name);
            $this->view->setVar('desc',$desc);
            $this->view->setVar('smsg',$smsg);
            $this->view->form =  new DisposalServiceForm();
        }
    }

    private function yardmaintenanceForm(){
        if ($this->request->isPost()) {
            $zipcode = $this->request->getPost('zipcode');
            $service = $this->request->getPost('service');
            $rate    = $this->sys->getRateById($service);
            $name    = $this->sys->getServiceNameById($service);
            $desc    = $this->sys->getServiceDescriptionById($service);
            $smsg    = $this->sys->getServiceMessage();
            $this->view->setVar('zipcode',$zipcode);
            $this->view->setVar('service',$service);
            $this->view->setVar('rate',$rate);
            $this->view->setVar('name',$name);
            $this->view->setVar('desc',$desc);
            $this->view->setVar('smsg',$smsg);
            $this->view->form = new YardMaintenanceServiceForm();
        }
    }

}